frontendv2/urls.py
from django.contrib import admin
from django.urls import path

from frontendv2.views.dashboard import Dashboard
from frontendv2.views.members import Members, MemberProfile, MemberMerge, AllMembers, MemberEdit, tag_member, add_note, GiftManager
from frontendv2.views.conversations import Conversations
from frontendv2.views.contributions import Contributions
from frontendv2.views.connections import Connections
from frontendv2.views.sources import Sources, Channels, tag_channel
from frontendv2.views.tags import Tags, AddTag, EditTag
from frontendv2.views.suggestions import MemberMergeSuggestions
from frontendv2.views.community import Managers, InviteManager, AcceptManager, Gifts, GiftTypeManager
from frontendv2.views.projects import Projects, ProjectAdd, ProjectOverview, ProjectEdit, ProjectThresholdEdit, ProjectTaskEdit, ProjectTaskAdd
from frontendv2 import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('community/new', views.new_community, name='add-community'),

    path('dashboard/<int:community_id>/', Dashboard.as_view, name='dashboard'),
    path('members/<int:community_id>/', Members.as_view, name='members'),
    path('members/<int:community_id>/all', AllMembers.as_view, name='all_members'),
    path('member/<int:member_id>/', MemberProfile.as_view, name='member_profile'),
    path('member/<int:member_id>/edit', MemberEdit.as_view, name='member_edit'),
    path('member/<int:member_id>/merge', MemberMerge.as_view, name='member_merge'),
    path('member/<int:member_id>/tag', tag_member, name='member_tag_form'),
    path('member/<int:member_id>/note', add_note, name='member_note_form'),
    path('member/<int:member_id>/gift', GiftManager.add_view, name='gift_add'),
    path('member/<int:member_id>/gift/<int:gift_id>/', GiftManager.edit_view, name='gift_edit'),
    path('conversations/<int:community_id>/', Conversations.as_view, name='conversations'),
    path('contributions/<int:community_id>/', Contributions.as_view, name='contributions'),
    path('connections/<int:community_id>/', Connections.as_view, name='connections'),
    path('connections/<int:community_id>/json', Connections.as_json, name='connections_json'),
    path('suggest/<int:community_id>/merge', MemberMergeSuggestions.as_view, name='member_merge_suggestions'),

    path('projects/<int:community_id>/', Projects.as_view, name='projects'),
    path('projects/<int:community_id>/add', ProjectAdd.as_view, name='project_add'),
    path('projects/<int:community_id>/overview/<int:project_id>/', ProjectOverview.as_view, name='project_overview'),
    path('projects/<int:community_id>/overview/<int:project_id>/edit', ProjectEdit.as_view, name='project_edit'),
    path('projects/<int:community_id>/overview/<int:project_id>/thresholds', ProjectThresholdEdit.as_view, name='project_threshold_edit'),
    path('projects/<int:community_id>/overview/<int:project_id>/task/add', ProjectTaskAdd.as_view, name='project_task_add'),
    path('projects/<int:community_id>/overview/<int:project_id>/task/<int:task_id>/', ProjectTaskEdit.as_view, name='project_task_edit'),
    path('projects/<int:community_id>/overview/<int:project_id>/task/done', ProjectOverview.mark_task_done, name='project_task_done'),
    path('gifts/<int:community_id>/', Gifts.as_view, name='gifts'),
    path('gifts/<int:community_id>/add', GiftTypeManager.add_view, name='gift_type_add'),
    path('gifts/<int:community_id>/edit/<int:type_id>/', GiftTypeManager.edit_view, name='gift_type_edit'),
    path('managers/<int:community_id>/', Managers.as_view, name='managers'),
    path('managers/<int:community_id>/invite', InviteManager.as_view, name='manager_invite'),
    path('managers/<int:community_id>/accept', AcceptManager.as_view, name='manager_accept'),
    path('sources/<int:community_id>/', Sources.as_view, name='sources'),
    path('sources/<int:community_id>/json', Sources.as_json, name='members_json'),
    path('sources/<int:community_id>/channels/<int:source_id>/', Channels.as_view, name='channels'),
    path('sources/<int:community_id>/channels/<int:source_id>/tag', tag_channel, name='channel_tag_form'),
    path('tags/<int:community_id>/', Tags.as_view, name='tags'),
    path('tags/<int:community_id>/add', AddTag.as_view, name='tag_add'),
    path('tag/<int:tag_id>/edit', EditTag.as_view, name='tag_edit'),
]

savannah/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('frontendv2.urls')),
    path('slack/', include('corm.plugins.slack')),
    path('github/', include('corm.plugins.github')),
    path('discourse/', include('corm.plugins.discourse')),
    path('discord/', include('corm.plugins.discord')),
    path('rss/', include('corm.plugins.rss')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except:
        # django-debug-toolbar is not installed
        pass

corm/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User, Group
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from imagekit import ImageSpec
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from corm.connectors import ConnectionManager

class Icon(ImageSpec):
    processors = [ResizeToFill(32, 32)]
    format = 'PNG'

    
    # Create your models here.

class UserAuthCredentials(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    connector = models.CharField(max_length=256, choices=ConnectionManager.CONNECTOR_CHOICES)
    server = models.CharField(max_length=256, null=True, blank=True)
    auth_id = models.CharField(max_length=256, null=True, blank=True)
    auth_secret = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return "%s on %s" % (self.user, ConnectionManager.display_name(self.connector))

class Community(models.Model):
    class Meta:
        verbose_name = _("Community")
        verbose_name_plural = _("Communities")
        ordering = ("name",)
    name = models.CharField(verbose_name="Community Name", max_length=256)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    managers = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True)
    logo = models.ImageField(upload_to='community_logos', null=True)
    icon = ImageSpecField(source='logo', spec=Icon)

    @property
    def default_project(self):
        return Project.objects.get(community=self, default_project=True)

    @property
    def icon_path(self):
        try:
            return self.icon.url
        except:
            return "%ssavannah/Savannah32.png" % settings.STATIC_URL

    def bootstrap(self):
        if self.managers is None:
            self.managers = Group.objects.create(name="%s Managers (%s)" % (self.name, self.id))
            self.owner.groups.add(self.managers)
            self.save()
        Tag.objects.get_or_create(name="thankful", community=self, defaults={'color':"aff5ab", 'keywords':"thanks, thank you, thx, thank yo"})
        Tag.objects.get_or_create(name="greeting", community=self, defaults={'color':"abdef5", 'keywords':"welcome, hi, hello"})
        Project.objects.get_or_create(community=self, default_project=True, defaults={'name': self.name, 'owner':None, 'threshold_user':1, 'threshold_participant':10, 'threshold_contributor':1, 'threshold_core':10})
            
    def __str__(self):
        return self.name

class Tag(models.Model):
    class Meta:
        ordering = ("name",)
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    color = models.CharField(max_length=16)
    keywords = models.CharField(max_length=256, null=True, blank=True, help_text=_("Comma-separated list of words. If found in a conversation, this tag will be applied."))

    def __str__(self):
        return "%s (%s)" % (self.name, self.community)

class TaggableModel(models.Model):
    class Meta:
        abstract = True
    tags = models.ManyToManyField(Tag, blank=True)

class ImportedDataModel(models.Model):
    class Meta:
        abstract = True
    origin_id = models.CharField(max_length=256, null=True, blank=True, unique=False)

class MemberConnection(models.Model):
    class Meta:
        ordering = ("-first_connected",)
    from_member = models.ForeignKey('Member', on_delete=models.CASCADE)
    to_member = models.ForeignKey('Member', on_delete=models.CASCADE, related_name='connectors')
    via = models.ForeignKey('Source', on_delete=models.SET_NULL, null=True)
    first_connected = models.DateTimeField(db_index=True)
    last_connected = models.DateTimeField(db_index=True)
    
    def __str__(self):
        return "%s -> %s" % (self.from_member, self.to_member)

class Member(TaggableModel):
    COMMUNITY = "community"
    STAFF = "staff"
    BOT = "bot"
    MEMBER_ROLE = [
        (COMMUNITY, 'Community'),
        (STAFF, 'Staff'),
        (BOT, 'Bot'),
    ]
    ROLE_NAME = {
        COMMUNITY: "Community",
        STAFF: "Staff",
        BOT: "Bot"
    }
    class Meta:
        ordering = ("name",)
        unique_together = [["community", "user"]]
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=256, db_index=True)
    first_seen = models.DateTimeField(auto_now_add=False, db_index=True)
    last_seen = models.DateTimeField(db_index=True, null=True, blank=True)

    email_address = models.EmailField(null=True, blank=True)
    mailing_address = models.CharField(max_length=256, null=True, blank=True)
    phone_number = models.CharField(max_length=32, null=True, blank=True)
    avatar_url = models.URLField(null=True, blank=True)
    role = models.CharField(max_length=32, choices=MEMBER_ROLE, default=COMMUNITY)

    connections = models.ManyToManyField('Member', through='MemberConnection')

    def is_connected(self, other):
        return MemberConnection.objects.filter(from_member=self, to_member=other).count() > 0

    def add_connection(self, other, source, timestamp=None):
        if self.id == other.id:
            return
        if self.is_connected(other):
            MemberConnection.objects.filter(from_member=self, to_member=other, last_connected__lt=timestamp).update(last_connected=timestamp)
            MemberConnection.objects.filter(from_member=other, to_member=self, last_connected__lt=timestamp).update(last_connected=timestamp)
        else:              
            MemberConnection.objects.create(from_member=self, to_member=other, via=source, first_connected=timestamp, last_connected=timestamp)
            MemberConnection.objects.create(from_member=other, to_member=self, via=source, first_connected=timestamp, last_connected=timestamp)
        
    def remove_connection(self, other):
        MemberConnection.objects.filter(from_member=self, to_member=other).delete()
        MemberConnection.objects.filter(from_member=other, to_member=self).delete()
        
    @property
    def icon_name(self):
        if self.role == Member.BOT:
            return "fas fa-robot"
        elif self.role == Member.STAFF:
            return "fas fa-user-tie"
        else:
            return "fas fa-user"

    def __str__(self):
        return self.name

    def merge_with(self, other_member):
        if self.user is None and other_member.user is not None :
            self.user = other_member.user
        if other_member.first_seen is not None and (self.first_seen is None or self.first_seen > other_member.first_seen):
            self.first_seen = other_member.first_seen
        if other_member.last_seen is not None and (self.last_seen is None or self.last_seen < other_member.last_seen):
            self.last_seen = other_member.last_seen
        if other_member.role == Member.BOT:
            self.role = Member.BOT
        elif other_member.role == Member.STAFF and self.role != Member.BOT:
            self.role = Member.STAFF
        if self.email_address is None and other_member.email_address is not None:
            self.email_address = other_member.email_address
        self_contacts = [c.detail for c in self.contact_set.all()]
        other_contacts = [c.detail for c in other_member.contact_set.all()]
        if other_member.name is not None and self.name in self_contacts and other_member.name not in other_contacts:
            self.name = other_member.name

        Contact.objects.filter(member=other_member).update(member=self)
        Note.objects.filter(member=other_member).update(member=self)
        MemberConnection.objects.filter(from_member=other_member).update(from_member=self)
        MemberConnection.objects.filter(to_member=other_member).update(to_member=self)
        Contribution.objects.filter(author=other_member).update(author=self)

        for tag in other_member.tags.all():
            self.tags.add(tag)

        Conversation.objects.filter(speaker=other_member).update(speaker=self)
        for convo in Conversation.objects.filter(participants=other_member):
            convo.participants.add(self)
            convo.participants.remove(other_member)

        for task in Task.objects.filter(stakeholders=other_member):
            task.stakeholders.add(self)
            task.stakeholders.remove(other_member)

        for level in MemberLevel.objects.filter(member=other_member):
            try:
                self_level = MemberLevel.objects.get(community=self.community, project=level.project, member=self)
                if level.level > self_level.level:
                    self_level.level = level.level
                    self_level.timestamp = level.timestamp
                    self_level.save()
            except MemberLevel.DoesNotExist:
                level.member = self
                level.save()
        self.save()
        other_member.delete()

class GiftType(models.Model):
    class Meta:
        ordering = ('discontinued', 'name')
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    contents = models.TextField()
    discontinued = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        if self.discontinued is not None:
            return "%s (discontinued)" % self.name
        else:
            return self.name

class Gift(models.Model):
    class Meta:
        ordering = ('-sent_date',)
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    gift_type = models.ForeignKey(GiftType, on_delete=models.SET_NULL, null=True, blank=False)
    reason = models.TextField(blank=True)
    sent_date = models.DateTimeField()
    received_date = models.DateTimeField(null=True, blank=True)

frontendv2/views/suggestions.py
import operator
from functools import reduce
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import F, Q, Count, Max
from django.contrib import messages

from corm.models import *
from corm.connectors import ConnectionManager
from frontendv2.views import SavannahView

class MemberMergeSuggestions(SavannahView):
    def __init__(self, request, community_id):
        super().__init__(request, community_id)
        self.active_tab = "members"
    
    @property
    def all_suggestions(self):
        suggestions = SuggestMemberMerge.objects.filter(community=self.community, status__isnull=True).order_by("-created_at")
        return suggestions

    @login_required
    def as_view(request, community_id):
        view = MemberMergeSuggestions(request, community_id)

        if request.method == 'POST':
            if 'reject' in request.POST:
                suggestion_id = request.POST.get('reject')
                suggestion = SuggestMemberMerge.objects.get(id=suggestion_id)
                suggestion.reject(request.user)
                messages.info(request, "Suggested rejected, you won't see it again")
            elif 'accept' in request.POST:
                selected = request.POST.getlist('selected')
                for suggestion_id in selected:
                    suggestion = SuggestMemberMerge.objects.get(id=suggestion_id)
                    suggestion.accept(request.user)
                if len(selected) > 0:
                    messages.success(request, "<b>%s</b> %s been merged" % (len(selected), pluralize(len(selected), "Member has", "Members have")))
                else:
                    messages.warning(request, "You haven't selected any merge suggestions")

            return redirect('member_merge_suggestions', community_id=community_id)
        return render(request, 'savannahv2/member_merge_suggestions.html', view.context)

frontendv2/templates/savannahv2/all_members.html
{% extends "savannahv2/base.html"%}
{% load static %}

{% block page_title %} | {{view.community.name}} Search{% endblock %}

{% block page_content %}
          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Members</h1>
            {% include 'savannahv2/filter_button.html' with current_tag=view.tag%}
          </div>

          <!-- Content Row -->

          <!-- Content Row -->
          <div class="row">

            <!-- Content Column -->
            <div class="col-lg-12 mb-4">

              <!-- All Members -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">All Members</h6>
                </div>
                <div class="card-body p-0">
                <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Member</th>
                    <th scope="col">Role</th>
                    <th scope="col">Joined</th>
                    <th scope="col">Last Seen</th>
                  </tr>
                </thead>
                <tbody>
                {% for member in view.all_members %}
                <tr>
                  <td>
                    <a href="{% url 'member_profile' member.id %}">{{ member.name }}</a>
                    {% if member.tag_count %}{% include 'savannahv2/tag_list.html' with tags=member.tags.all %}{% endif %}
                  </td>
                  <td>{{member.get_role_display}}</td>
                  <td>{{member.first_seen}}</td>
                  <td>{{member.last_seen}}</td>
                </tr>
                {% if member.note_count %}
                <tr><td colspan=3>
                <ul>
                {% for note in member.note_set.all %}
                <li><span class="note">{{note}}</span></li>
                {% endfor %}
                </ul>
                </td></tr>
                {% endif %}
                {% endfor %}
                </tbody>
                </table>

                {% if view.has_pages %}
                <nav aria-label="Member table pages">
                  <ul class="pagination justify-content-center">
                    <li class="page-item {% if view.page <= 1 %}disabled{% endif %}">
                      <a class="page-link" href="?{% if view.search %}search={{view.search}}&{% endif %}page=1" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                      </a>
                    </li>
                    {% for page in view.page_links %}
                      <li class="page-item{% if view.page == page %} active{% endif %}"><a class="page-link" href="?{% if view.search %}search={{view.search}}&{% endif %}page={{page}}">{{page}}</a></li>
                    {% endfor %}
                    <li class="page-item{% if view.page >= view.last_page %} disabled{% endif %}">
                      <a class="page-link" href="?{% if view.search %}search={{view.search}}&{% endif %}page={{view.last_page}}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">{{Next}}</span>
                      </a>
                    </li>
                  </ul>
                </nav>
                {% endif %}

                </div>
              </div>

            </div>
          </div>
        </div>
        <!-- /.container-fluid -->
{% endblock %}

frontendv2/templates/savannahv2/filter_button.html
          <span id="filter-bar" class="">
            <span class="dropdown">
            {% if view.timespan == view.MAX_TIMESPAN %}
              <button class="btn btn-light text-muted dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-calendar"></i> Past Year</button>
            {% else %}
              <button style="white-space:nowrap;" class="btn dropdown-toggle btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="{{view.timespan_icon}}"></i> {{view.timespan_display}}</button>
            {% endif %}
              <div class="dropdown-menu animated--fade-in " aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}timespan={{view.MAX_TIMESPAN}}"><i class="fas fa-calendar"></i> Past Year</a>
                    <a class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}timespan=180"><i class="fas fa-calendar-plus"></i> 6 Months</a>
                    <a class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}timespan=30"><i class="fas fa-calendar-alt"></i> 30 Days</a>
                    <a class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}timespan=7"><i class="fas fa-calendar-week"></i> Last Week</a>
                    <a class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}timespan=1"><i class="fas fa-calendar-day"></i> Today</a>
              </div>
            </span>
            <span class="dropdown">
            {% if view.role %}
              <button style="white-space:nowrap;" class="btn dropdown-toggle btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="{% if view.role == "community"%}fas fa-user{% elif view.role == "staff" %}fas fa-user-tie{% else %}fas fa-robot{% endif %}"></i> {% if view.role == "community"%}Community{% elif view.role == "staff" %}Staff{% else %}Bots{% endif %}</button>
            {% else %}
              <button class="btn btn-light text-muted dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-users"></i> Roles</button>
            {% endif %}
              <div class="dropdown-menu animated--fade-in " aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}role="><i class="fas fa-users"></i> All Members</a>
                    <a class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}role=community"><i class="fas fa-user"></i> Community</a>
                    <a class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}role=staff"><i class="fas fa-user-tie"></i> Staff</a>
                    <a class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}role=bot"><i class="fas fa-robot"></i> Bots</a>
              </div>
            </span>
            <span class="dropdown">
            {% if view.tag %}
              <button style="white-space:nowrap; color:#5a5c69; background-color: #{{view.tag.color}};" class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-hashtag"></i> {{view.tag.name}}</button>
            {% else %}
              <button class="btn btn-light text-muted dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-tags"></i> Tags</button>
            {% endif %}
              <div class="dropdown-menu animated--fade-in " aria-labelledby="dropdownMenuButton">
                    <a style="white-space:nowrap; color:#5a5c69;" class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}tag="><i class="fas fa-times"></i> Clear</a>
                    {% for tag in view.community.tag_set.all %}
                    <a style="white-space:nowrap; color:#5a5c69; background-color: #{{tag.color}};" class="dropdown-item p-2" href="?{% if view.search %}search={{view.search}}&{% endif %}tag={{tag.name}}"><i class="fas fa-hashtag"></i> {{tag.name}}</a>
                    {% endfor %}
              </div>
            </span>
            {% if view.tag or view.role or view.timespan != view.MAX_TIMESPAN %}
            <a class="align-baseline text-secondary" href="?{% if view.search %}search={{view.search}}&{% endif %}timespan=&role=&tag=" title="Clear filters"><i class="fas fa-times"> </i></a>
            {% endif %}
          <span>

frontendv2/templates/savannahv2/home.html
{% extends "savannahv2/blank.html" %}
{% load humanize static %}

{% block page_title %} | Communities{% endblock %}

{% block page_content %}
{% if communities %}

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
<h1 class="h1 mb-0 text-white">Your Communities</h1>
</div>

<!-- Content Row -->
<div class="row">

{% for community in communities %}
<!-- Members Card -->
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card shadow h-100 py-2">
    <a href="{% url 'dashboard' community.id %}">
    <div class="card-body">
        <div class="row no-gutters align-items-center">
        <div class="col mr-2">
            <div class="h5 font-weight-bold text-gray-800 text-uppercase mb-1">{{community.name}}</div>
            <div class="text-sm mb-0 font-weight-bold text-gray-800">{{community.member_set.all.count|intcomma}} Members</div>
        </div>
        <div class="col-auto">
            <img src="{{community.icon_path}}">
        </div>
        </div>
    </div>
    </a>
    </div>
</div>
{% endfor %}

</div>
<!-- End row -->

{% else %}

<!-- Content Row -->
<div class="row mt-5 justify-content-center">
<div class="col-xl-6 col-md-6 mb-8 mt-8 align-items-center">
<center>
    <div class="card shadow h-100 py-2">
    <div class="card-body">
        <div class="align-items-center">
            <h2>You have no communities</h2>
            <img id="logo" src="{% static 'savannah/Savannah256.png' %}" />
            <div>

            {% if BETA %}
                {% if OPEN_BETA %}
                <p>Savannah is currently in a open-beta program. </p>
                <p>You can get free early-access to Savannah to help us test it and provide feedback while we build it.</p>
                <p><a class="btn btn-primary" href="{% url 'add-community' %}">Become a Beta Tester</a></p>
                {% else %}
                <p>Savannah is currently in a closed-beta program. </p>
                <p>If you would like to become a beta-tester, <a href="https://join.slack.com/t/savannahcommunity/shared_invite/zt-fi84m113-JhDiFgN7J0h6DPL~FlwT7w" target="_blank">join our Slack</a></p>
                {% endif %}
            {% else %}
            <a class="btn btn-success mt-3" href="{% url 'add-community' %}">Start Your Community</a>
            {% endif %}
            </div>
        </div>
    </div>
    </div>
</center>
</div>
</div>
<!-- End row -->

{% endif %}

{% endblock %}

frontendv2/templates/savannahv2/index.html
{% extends "savannahv2/blank.html" %}
{% load humanize static %}

{% block page_content %}

<!-- Content Row -->
<div class="row mt-5 justify-content-center">
<div class="col-xl-6 col-md-6 mb-8 mt-8 align-items-center">
<center>
    <div class="card shadow h-100 py-2">
    <div class="card-body">
        <h2>Coming Soon...</h2>
        <img id="logo" src="{% static 'savannah/Savannah256.png' %}" />
        <div id="content">
            <h1>Savannah</h1>
            {{ sayings|random }}
        </div>
    </div>
    </div>
</center>
</div>
</div>
<!-- End row -->

{% endblock %}

frontendv2/templates/savannahv2/piechart_script.html
<script>
var ctx = document.getElementById("{{chart.id}}");
var myPieChart = new Chart(ctx, {
  type: 'doughnut',
  data: {
    labels: {{chart.get_data_names|safe}},
    datasets: [{
      data: {{chart.get_data_values|safe}},
      backgroundColor: {{chart.get_data_colors|safe}},
      hoverBorderColor: "rgba(234, 236, 244, 1)",
    }],
  },
  options: {
    maintainAspectRatio: false,
    tooltips: {
      backgroundColor: "rgb(255,255,255)",
      bodyFontColor: "#858796",
      borderColor: '#dddfeb',
      borderWidth: 1,
      xPadding: 15,
      yPadding: 15,
      displayColors: false,
      caretPadding: 10,
    },
    legend: {
      display: true
    },
    cutoutPercentage: 0,
  },
});
</script>